### ISSUE TITLE
timeout unit default value is wrong in WaitForIdle.java

### ISSUE THREAD

**Issue by truebit** [appium/appium-android-bootstrap#23]
Code here: https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/handler/WaitForIdle.java#L49
It used `timeout=10` for default value.

Actually, `UiDevice.waitForIdle(long timeout)` with param in milliseconds: https://android.googlesource.com/platform/frameworks/testing/+/master/uiautomator/library/core-src/com/android/uiautomator/core/UiDevice.java#483

So maybe you the default value should be `10000`

**Comment by imurchie** [comment]
I don't see where this code is actually used. The Android driver never seems to call it.

**Comment by truebit** [comment]
Maybe. Do you know where could achieve [`setWaitForIdleTimeout`](https://developer.android.com/reference/android/support/test/uiautomator/Configurator.html#setWaitForIdleTimeout%28long%29) in UiAutomator class in appium? something like any desired capability in appium?

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7498](https://github.com/appium/appium/issues/7498) via [**ZenHub**](https://www.zenhub.com/)
