### ISSUE TITLE
How to build AppiumBootstrap.jar

### ISSUE THREAD

**Issue by haluong** [appium/appium-android-bootstrap#39]
Hi all,

I tried to build AppiumBootstrap.jar by doing the steps as https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/README.md, and I got bootstrap-1.0.0-SNAPSHOT.jar. 
I installed Appium by using AppiumForWindows_1_4_13_1.zip. And I renamed bootstrap-1.0.0-SNAPSHOT.jar to AppiumBootstrap.jar, ran Appium and has the error
> info: [debug] spawning: C:\Users\{Window user}\AppData\Local\Android\sdk\platform-tools\adb.exe -s 169.254.138.177:5555 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.microsoft.office.outlook -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker:
> info: [debug] [UIAUTOMATOR STDOUT] libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: shortMsg=java.lang.RuntimeException
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: longMsg=Didn't find class "io.appium.android.bootstrap.Bootstrap" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/uiautomator.jar", zip file "/data/local/tmp/AppiumBootstrap.jar"],nativeLibraryDirectories=[/system/lib]]
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_CODE: 0
> info: [debug] UiAutomator exited
 
Could you please help me the issue? How can I rebuild AppiumBootstrap.jar?

Thanks,
Ha

**Comment by jlipps** [comment]
Appium builds the bootstrap for you, there is no need to build it yourself. Why are you trying to do this?

**Comment by haluong** [comment]
I'd like to contribute to Appium code, is that possible? How can I get started?

**Comment by jlipps** [comment]
Yes, check out https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/developers-overview.md for information on contributing. To rebuild the AppiumBootstrap.jar, you can simply run `gulp ant-build`. This also happens on NPM install etc.
